### ISSUE TITLE
为什么代码这么长啊

### ISSUE THREAD

**Issue by zry9815** [ybm911/FUCK_jiankangdaka#1]
0基础 我们学校也是简道云 前面编了一个post 云函数 X-CSRF-Token是动态的 提交了就响应已经打卡 每次刷新网页都会变化 不知道怎么办了 源码标头有一个<meta name="csrf-token" content="(XXXXX)">

**Comment by ybm911** [comment]
X-CSRF-Token 是为了防止跨站请求伪造的，这个目前没有找到好的办法去解决，所以此脚本中还是得手动填写。每次刷新网页都会变化？源码标头有一个？没太明白你的意思

**Comment by ybm911** [comment]
> 0基础 我们学校也是简道云 前面编了一个post 云函数 X-CSRF-Token是动态的 提交了就响应已经打卡 每次刷新网页都会变化 不知道怎么办了 源码标头有一个

X-CSRF-Token 是为了防止跨站请求伪造的，这个目前没有找到好的办法去解决，所以此脚本中还是得手动填写。每次刷新网页都会变化？源码标头有一个？没太明白你的意思

**Comment by zry9815** [comment]
&nbsp;每次刷新网页都会变化&nbsp; &nbsp;X-CSRF-Token和

一致





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elli0t"<notifications@github.com&gt;; 
发送时间: 2020年12月28日(星期一) 晚上10:19
收件人: "ybm911/FUCK_jiankangdaka"<FUCK_jiankangdaka@noreply.github.com&gt;; 
抄送: "1401481082"<1401481082@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ybm911/FUCK_jiankangdaka] 为什么代码这么长啊 (#1)





  
0基础 我们学校也是简道云 前面编了一个post 云函数 X-CSRF-Token是动态的 提交了就响应已经打卡 每次刷新网页都会变化 不知道怎么办了 源码标头有一个
  
X-CSRF-Token 是为了防止跨站请求伪造的，这个目前没有找到好的办法去解决，所以此脚本中还是得手动填写。每次刷新网页都会变化？源码标头有一个？没太明白你的意思
